<a href="https://colab.research.google.com/github/tayyib-saddique/bbk-ds/blob/main/week1/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Relevant Python modules: Numpy

Start this exercise notebook during the tutorial session, you can complete it as homework.

Please also see the [online Numpy resources](https://numpy.org/learn/).

Installation:

```bash
pip install numpy
```

In [ ]:
# check that your kernel 'knows' numpy

import numpy as np

#### Create an array consisting of 2 rows and 5 columns, containing with the first 10 integers

In [ ]:
my_array = np.arange(10)

print(my_array)
reshaped_array=my_array.reshape(2,5)
print(reshaped_array)

my_array.round


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


<function ndarray.round>

##### Use the appropriate methods to print out the shape of the array and the total number of elements

In [ ]:
print(reshaped_array.shape)

(3, 3)


##### What's the sum of the values in each row?

In [ ]:
print(reshaped_array.sum(axis=0))
print(reshaped_array.shape)
reshaped_array.sum(axis=0)/reshaped_array.shape[0]

[ 5  7  9 11 13]
(2, 5)


array([2.5, 3.5, 4.5, 5.5, 6.5])

##### Generate a 3x3 unit/identity matrix:

$$
U_{3\times 3}  =  
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
$$

In [ ]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##### Generate a 2x3 matrix with values sampled from a standard normal distribution

Have a look at the [online documentation](https://numpy.org/doc/stable/reference/random/index.html).

In [ ]:
# look at the np.random documentation to sample data
print(np.random.randn(10000,15000))

[[ 4.77112624e-01 -8.16468557e-02 -8.54401699e-01 ...  3.30784301e-01
  -6.53922308e-01  1.57193704e+00]
 [ 7.70526333e-01  3.82313334e-01  1.22191405e+00 ... -1.12863221e-03
  -3.43567338e-01  2.50459384e-01]
 [-1.22755503e+00  1.45183584e+00 -9.36843962e-01 ...  2.81292210e-01
   3.60640632e-02 -1.26956426e+00]
 ...
 [-1.21354460e+00  4.63059613e-01  2.34900635e-01 ...  1.04681454e+00
   2.07777559e-02  1.25299839e+00]
 [ 8.22799999e-01 -6.31971892e-01  1.26370698e+00 ... -7.90789927e-01
  -8.65754612e-01  1.80419797e-02]
 [-9.86131159e-01  2.31604903e-02  1.08445702e+00 ...  3.38145951e-01
   6.98718463e-01 -8.64287682e-01]]
